 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2_vicuna_instruct
  model_type: vicuna7b_pretrain
  load_pretrained: True
  load_finetuned: True
  vit_model: eva_clip_g
  pretrained: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/blip2/blip2_vicuna7b/blip2_pretrained_vicuna7b.pth"
  finetuned: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/vicuna7b/qformer_moe_post/lora_mix_coco_gqa_aokvqa_raw_QformerMoE_lr5e5_textinqf_6epo_0308/20240309000/checkpoint_7.pth"
  q_former_model: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/blip2/blip2_vicuna7b/blip2_pretrained_vicuna7b.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"

  # Q-Former
  num_query_token: 32
  qformer_text_input: True

  # vicuna
  llm_model: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/vicuna-7b-v1.1"
  lora_r: 64 # freeze_llm = False
  lora_alpha: 16
  prompt: ""
  max_txt_len: 256
  max_output_txt_len: 256

  # freeze
  freeze_vit: True
  freeze_llm: False
  freeze_qformer: False
  freeze_t5_proj: False

  # moe
  use_moeqformer: False
  use_route_moe: False
  # use_moeqformer: True
  # use_route_moe: True
  # moebert_route_method: "post-route"
  # moebert_load_balance: 0.05
  # moebert_expert_num: 3
  # moebert_num_beams: 3
  # moe_weight_type: 'ffn_prob'
  # use_balance_loss: False
  # ln_position: "out"
  # gate_save_path: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/vicuna7b/qformer_moe_route/route_save/lora_mix_coco_gqa_ao_cap_raw_QformerMoE_Post_Route_linear_gate_lnout_lr5e5_3ex3b_2loss_005_top6layer_textinqf_8epo_0309/"

datasets:
  # gqa:
  #   type: balanced_sft_raw_eval
  #   batch_size: 8
  #   vis_processor:
  #     eval:
  #       name: "blip2_image_eval"
  #       image_size: 224
  #   text_processor:
  #     eval:
  #       name: "blip_caption"

  coco_vqa:    # 658104
    type: vqa_v2_eval
    batch_size: 32
    vis_processor:
      eval:
        name: "blip2_image_eval"
        image_size: 224
    text_processor:
      eval:
        name: "blip_caption"

  # coco_caption: # 414113 train
  #   type: coco_cap_eval
  #   batch_size: 8
  #   vis_processor:
  #     eval:
  #       name: "blip2_image_eval"
  #       image_size: 224
  #   text_processor:
  #     eval:
  #       name: "blip_caption"
  
  # ok_vqa: # train, valid (9009, 5046)
  #   type: ok_vqa_eval
  #   batch_size: 8
  #   vis_processor:
  #     eval:
  #       name: "blip2_image_eval"
  #       image_size: 224
  #   text_processor:
  #     eval:
  #       name: "blip_caption"

  # aok_vqa: # train: 17056, val: 1145
  #   batch_size: 8
  #   vis_processor:
  #     eval:
  #       name: "blip2_image_eval"
  #       image_size: 224
  #   text_processor:
  #     eval:
  #       name: "blip_caption"
run:
  task: instruction_tuning
  seed: 42
  output_dir: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/vicuna7b/qformer_moe_route/eval/lora_mix_coco_gqa_aokvqa_raw_QformerMoE_lr5e5_textinqf_6epo_0308/"
  num_workers: 4
  
  amp: True
  resume_ckpt_path: null

  evaluate: True
  # test_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  
