 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2_vicuna_instruct
  model_type: vicuna7b_pretrain
  load_pretrained: True
  load_finetuned: True
  vit_model: eva_clip_g
  pretrained: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/blip2/blip2_vicuna7b/blip2_pretrained_vicuna7b.pth"
  finetuned: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/vicuna7b/qformer_moe_route/mix_1048k_raw_QformerMoE_Route_Post_NoNorm_5ex_2beam_1loss_top3layer_textinqf_epo6_1215/20231216161/checkpoint_best.pth"
  q_former_model: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/blip2/blip2_vicuna7b/blip2_pretrained_vicuna7b.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"

  # Q-Former
  num_query_token: 32
  qformer_text_input: True

  # T5
  llm_model: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/vicuna-7b-v1.1"
  prompt: ""
  max_txt_len: 256
  max_output_txt_len: 256

  # freeze
  freeze_vit: True
  freeze_llm: True
  freeze_qformer: False
  freeze_t5_proj: False

  # moe
  use_moeqformer: True
  use_route_moe: True
  moebert_route_method: "post-route"
  moebert_expert_num: 5
  moebert_num_beams: 2

datasets:
  ok_vqa: # train, valid (9009, 5046)
    batch_size: 32
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  vizwiz:
    eval_file_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/VizWiz/val.json
    img_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/VizWiz/val    
    max_new_tokens: 20
    batch_size: 10
  # iconvqa:
  #   eval_file_path: /path/to/eval/annotation/path  
  #   img_path: /path/to/eval/image/path    
  #   max_new_tokens: 20
  #   batch_size: 10
  # vsr:
  #   eval_file_path: cambridgeltl/vsr_zeroshot 
  #   img_path: /path/to/eval/image/path    
  #   max_new_tokens: 20
  #   batch_size: 10
  hm:
    eval_file_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/hm_data/dev_seen.jsonl
    img_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/hm_data/
    max_new_tokens: 20
    batch_size: 100

run:
  task: instruction_tuning
  name: vqa_benchmark_evaluation
  save_path: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/vicuna7b/qformer_moe/eval/benchmarks/mix_1048k_raw_QformerMoE_Route_Post_NoNorm_5ex_2beam_1loss_top3layer_textinqf_epo6_1215/"
  seed: 42

  

  

