datasets:
  refcocop:
    data_type: images
    build_info:
      image_path: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/COCO
      ann_path: /path/to/refcoco_annotations
      dataset: refcoco+
      splitBy: unc