 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2_t5_qformer_moe
  model_type: flant5xxl
  load_pretrained: True
  load_finetuned: False
  vit_model: eva_clip_g
  pretrained: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/blip2/blip2-flant5-xxl/blip2_pretrained_flant5xxl.pth"
  finetuned: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/flant5xxl/base/mix_coco_gqa_ao_cocap_textcap_raw_QformerMoE_lr5e5_top6layer_textinqf_8epo_0328/20240328100/checkpoint_5.pth"
  q_former_model: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/blip2/blip2-flant5-xxl/blip2_pretrained_flant5xxl.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"

  # Q-Former
  num_query_token: 32
  qformer_text_input: True

  # vicuna
  llm_model: "/mnt/pfs-guan-ssai/nlu/wanghanzi/models/vicuna-7b-v1.1"
  prompt: ""
  max_txt_len: 256
  max_output_txt_len: 256

  # freeze
  freeze_vit: True
  freeze_llm: True
  freeze_qformer: False
  freeze_t5_proj: False

  # moe
  general_version: 'base'

datasets:
  coco_vqa:    # 658104
    type: vqa_v2_eval
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 224
      eval:
        name: "blip2_image_eval"
        image_size: 224
    text_processor:
      eval:
        name: "blip_caption"
      train:
        name: "blip_caption"

evaluation_datasets:
  vizwiz:
    eval_file_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/VizWiz/val.json
    img_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/VizWiz/val    
    max_new_tokens: 20
    batch_size: 32
  hm:
    eval_file_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/hm_data/dev_seen.jsonl
    img_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/hm_data/
    max_new_tokens: 20
    batch_size: 32
  vsr:
    eval_file_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/visual-spatial-reasoning/data
    img_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/visual-spatial-reasoning/images
    max_new_tokens: 20
    batch_size: 20
  nocap:
    eval_file_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/NoCap/nocaps_val.json
    img_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/NoCap/images
    max_new_tokens: 20
    batch_size: 20
    
run:
  task: instruction_tuning
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 5e-5
  min_lr: 1e-6
  warmup_lr: 1e-6
  log_freq: 5
  save_freq: 1500

  weight_decay: 0.05
  max_epoch: 10
  num_workers: 4
  warmup_steps: 600
  iters_per_epoch: 3000
  
  seed: 42
  output_dir: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/vicuna7b/qformer_mode_cls/eval/20240328100_ckpt5/"
  save_path: "/mnt/pfs-guan-ssai/nlu/wanghanzi/experiments/blip2/vicuna7b/qformer_mode_cls/eval/20240328100_ckpt5/"
  
  amp: True
  resume_ckpt_path: null

  evaluate: True
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  
