datasets:
  multitask_conversation:
    data_type: images
    build_info:
    
      image_path: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/COCO/train2014
      ann_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/minigptv2_llava_multitask_conv/multitask_conversation.json