datasets:

  llava_conversation:
    data_type: images
    build_info:
      image_path: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/COCO/train2014
      # ann_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/conversation_58k.json
      ann_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/llava_conver_single_turn_257k_clean_v2.json