datasets:
  llava_detail:
    data_type: images
    build_info:
      image_path: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/COCO/train2014
      ann_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/detail_23k.json