datasets:

  llava_reason:
    data_type: images
    build_info:
      image_path: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/COCO/train2014
      ann_path: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/complex_reasoning_77k.json