datasets:
  textcaps_caption:
    data_type: images
    
    build_info:
      annotations:
        train:
          storage:
              - /mnt/pfs-guan-ssai/nlu/wanghanzi/data/TextCap/TextCaps_0.1_train.json
        val:
          storage:
              - /mnt/pfs-guan-ssai/nlu/wanghanzi/data/TextCap/TextCaps_0.1_val.json
        test:
          storage:
              - /mnt/pfs-guan-ssai/nlu/wanghanzi/data/TextCap/TextCaps_0.1_test.json
      images:
          storage: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/TextVQA
